### ISSUE TITLE
Usage with linuxserver/unifi-controller and unifi-poller in docker-compose

### ISSUE THREAD

**Issue by thibmaek** [unifi-poller/unifi-poller#180]
I am trying to deploy this within a docker-compose stack I have running on my NUC. For the controller I am using the [linuxserver/unifi-controller](https://hub.docker.com/r/linuxserver/unifi-controller) image.

It seems that unifi-poller is unable to connect to the controller:

```shell
$ docker-compose up unifi_poller 
Creating unifi_poller ... done
Attaching to unifi_poller
unifi_poller    | 2020/01/21 21:39:24 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
unifi_poller    | 2020/01/21 21:39:24 [INFO] UniFi Poller v1.6.3-641 Starting Up! PID: 1
unifi_poller    | 2020/01/21 21:39:24 [ERROR] Controller Auth or Connection failed, but continuing to retry! unifi controller: Post https://127.0.0.1:8443/api/login: dial tcp 127.0.0.1:8443: connect: connection refused
unifi_poller    | 2020/01/21 21:39:24 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
unifi_poller    | 2020/01/21 21:39:54 [INFO] Logging Measurements to InfluxDB at http://127.0.0.1:8086 as user unifi
unifi_poller    | 2020/01/21 21:39:54 [INFO] Re-authenticating to UniFi Controller
unifi_poller    | 2020/01/21 21:39:54 [ERROR] unifi controller: Post https://127.0.0.1:8443/api/login: dial tcp 127.0.0.1:8443: connect: connection refused
```

__docker-compose.yml__

```yaml
version: '2'

services:
  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    env_file: .env
    environment:
      - MEM_LIMIT=1024M
    volumes:
      - ./data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 9876:6789
    restart: unless-stopped

  unifi_poller:
    container_name: unifi_poller
    image: golift/unifi-poller:stable
    volumes:
      - ./unifi_poller.conf:/etc/unifi-poller/up.conf
```

__unifi_poller.conf__

```toml
[unifi.defaults]
  role       = "https://172.17.0.1:8443" # Using docker's internal IP here
  url        = "https://172.17.0.1:8443"
  user       = "unifi-poller"
  pass       = "..."
  sites      = ["all"]
  save_ids   = false
  save_dpi   = false
  save_sites = true
  verify_ssl = false
```

It seems like there is something prohibiting me from accessing it in a web browser as well, but I thought disabling the verify_ssl directive would skip this check?

![image](https://user-images.githubusercontent.com/6213695/72845787-a1308680-3c9f-11ea-901d-5c8e3de688f9.png)

Any ideas? Since this will only be running locally, I want to skip every form of SSL or security, I will fix my security stuff once I start exposing it.
