### ISSUE TITLE
Make Prometheus docs better, fix input params.

### ISSUE THREAD

**Issue by davidnewhall** [unifi-poller/unifi-poller#190]
- Docs are too complicated.
- `input` should default to `unifi`
-  `path` should be `target`
- Consider `collect[]` approach
  -  There's examples for this in node_exporter, snmp_exporter, mysqld_exporter  
  -   https://github.com/prometheus/node_exporter#filtering-enabled-collectors

**Comment by davidnewhall** [comment]
```
scrape_configs:
  - job_name: 'unifipoller'
    static_configs:
      - targets:
        - https://unifi.controller:8443
        - https://another.controller:8443
    metrics_path: /scrape
    params:
      input: [unifi]
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: localhost:9130
```

**Comment by davidnewhall** [comment]
After the updates, my setup on unraid looks like this: 
```
  - job_name: 'unifipoller'
    static_configs:
      - targets:
        - 'https://unifi-controller:8443'
    metrics_path: /scrape
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 'UniFi-Poller:9130'
```
