### ISSUE TITLE
Site selection via env variables

### ISSUE THREAD

**Issue by ThomDietrich** [unifi-poller/unifi-poller#237]
Hey there,
could you please clarify how selecting a specific site works? In the MWE below I want to probe only one of two sites:

`docker-compose logs`
```
unifi_poller_1        | 2020/06/05 19:54:45 [INFO] UniFi Poller v2.0.0-760 Starting Up! PID: 1
unifi_poller_1        | 2020/06/05 19:54:46 [INFO] Found 2 site(s) on controller https://unifi.mydomain.de: mn6suw7u (XXX), ai6v9laa (YYY)
unifi_poller_1        | 2020/06/05 19:54:46 [INFO] Configured UniFi Controller at https://unifi.mydomain.de v5.12.72 as user unifipoller. Sites: [all]
unifi_poller_1        | 2020/06/05 19:54:46 [INFO] Prometheus config missing (or disabled), Prometheus HTTP listener disabled!
unifi_poller_1        | 2020/06/05 19:54:46 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
``` 

docker-compose.yml:
```yml
  unifi_poller:
    image: golift/unifi-poller:latest
    depends_on:
      - influxdb
    environment:
      - UP_PROMETHEUS_DISABLE=true
      - UP_INFLUXDB_DB=unifi
      - UP_INFLUXDB_USER=${INFLUXDB_WRITE_USERNAME}
      - UP_INFLUXDB_PASS=${INFLUXDB_WRITE_PASSWORD}
      - UP_INFLUXDB_URL=https://monitoring.mydomain.de:8086
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=https://unifi.mydomain.de
      - UP_UNIFI_DEFAULT_SITES_0="mn6suw7u"  # <-------------------------------
      - UP_POLLER_DEBUG=false
```

This should work according to https://github.com/unifi-poller/unifi-poller/wiki/Configuration

I would be happy to help improve documentation after I figured it out for my setup ;)

Thank you!
