### ISSUE TITLE
Docker: InfluxDB High CPU Usage

### ISSUE THREAD

**Issue by BClev** [unifi-poller/unifi-poller#257]
OS: Raspbian 10 - Buster
Hardware: Raspberry Pi 4 Model B Rev 1.2
Unifi-poller architecture: Docker-Compose with minimal config changes.

Opening this issue to help others using Unifi-Poller with Docker and experiencing the same issue.
InfluxDB was using 120-130% CPU on average until I made an influxdb.conf in the same folder as the docker-compose yaml with the following parameters (key to the fix is the "store-enabled = false" line, re: https://github.com/influxdata/influxdb/issues/9475):
```
[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  max-concurrent-compactions = 1

[monitor]
  store-enabled = false
  store-database = "_internal"
  store-interval = "10s"
```
And then edited the docker-compose file to run influxd with the config, and mount the config as read-only in the container:
```   
services:
  influxdb:
    restart: always
    image: influxdb:latest
    ports:
      - '8086:8086'
    command: influxd -config /etc/influxdb/influxdb.conf
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
```
The InfluxDB container CPU usage is down to 10-14% now. I don't know if this is an issue with the forthcoming InfluxDB 2.0.
