### ISSUE TITLE
Docs: Update example compose files in docs.

### ISSUE THREAD

**Issue by doodlemania2** [unifi-poller/unifi-poller#285]
Any thoughts on how we might add the Loki components to the Docker Compose section? I've tried a few different approaches, none seem to work very well - it is likely my docker compose foo is n00b :)

**Comment by davidnewhall** [comment]
A quick google search brings me to this: https://grafana.com/docs/loki/latest/installation/docker/
Which has this content:
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:1.6.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:1.6.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
```

Does that help?

**Comment by doodlemania2** [comment]
Yes! But was curious if adding to the official compose on this site might be advantageous so one could see config possibilities and environment variables in use. Just a thought 🙂

**Comment by davidnewhall** [comment]
I mean, it's a great idea. The problem is that I do not use docker compose myself, and would be testing my own knowledge while trying to test a new implementation. @jonbloom added the original docker compose file in this repo, and @davidyilee provided some fixes a few months back. Maybe one of them will see this ping and add some notes here. I'd gladly accept a contribution if someone wants to add Loki to the existing docker-compose ecosystem. I just don't think I'm the right guy for that.

**Comment by doodlemania2** [comment]
Fair enough :) Will keep tinkering to see if I can make it go and will contribute back if successful. Cheers!

**Comment by doodlemania2** [comment]
@jonbloom / @davidyilee I think the key bits here are what would be good to pass into poller in the compose file to make it send its data to loki :)

**Comment by lux4rd0** [comment]
I've been enjoying the Loki integration for a while now... sharing my docker-compose that allows for just Prometheus and Loki:

```
services:
  unifi-poller:
    container_name: unifi-poller
    environment:
      UP_INFLUXDB_DISABLE: "true"
      **UP_LOKI_URL: http://log01.tylephony.com:3100**
      UP_POLLER_DEBUG: "false"
      UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:9130
      UP_PROMETHEUS_NAMESPACE: unifipoller
      **UP_UNIFI_DEFAULT_PASS: password**
      UP_UNIFI_DEFAULT_SAVE_ALARMS: "true"
      UP_UNIFI_DEFAULT_SAVE_ANOMALIES: "true"
      UP_UNIFI_DEFAULT_SAVE_DPI: "true"
      UP_UNIFI_DEFAULT_SAVE_EVENTS: "true"
      UP_UNIFI_DEFAULT_SAVE_IDS: "true"
      UP_UNIFI_DEFAULT_SAVE_SITES: "true"
      UP_UNIFI_DEFAULT_URL: https://unifi.tylephony.com:443
      **UP_UNIFI_DEFAULT_USER: unifipoller**
    image: golift/unifi-poller:2.0.2-beta1
    logging:
      driver: loki
      options:
        loki-url: http://log01.tylephony.com:3100/loki/api/v1/push
    ports:
    - 9130:9130/tcp
    restart: always
version: '3.0'
```

Modify as needed :) Also - you can pull the Loki Docker logging driver if you don't have it installed...
