### ISSUE TITLE
Deploying UniFi-Poller On MicroK8S

### ISSUE THREAD

**Issue by ThePieMonster** [unifi-poller/unifi-poller#302]
I am trying to deploy the image on a MicroK8S cluster using the below YAML. The pod deploys but the config file is not being used. I created a ConfigMap in the default namespace called "unifi-poller".

```
kind: Pod
apiVersion: v1
metadata:
  name: unifi-poller
  namespace: default
spec:
  containers:
    - name: unifi-poller
      image: golift/unifi-poller
      volumeMounts:
      - name: default-volume-unifi-poller
        mountPath: /config/unifi-poller.conf
  volumes:
    # `name` here must match the name specified in the volume mount
    - name: default-volume-unifi-poller
    # Populate the volume with config map data
      configMap:
        # `name` here must match the name specified in the ConfigMap's YAML
        name: unifi-poller
```

What is the proper YAML setup for deploying the pod with a ConfigMap?

**Comment by davidnewhall** [comment]
I've never used Kubernetes and I'm not familiar with this configuration format. The config path `/config/unifi-poller.conf` is correct, so as long as you put a config file in that path poller will read it in. The poller startup messages print out the config file it's using. I don't see anything in this config that identifies where the config file is mounted _from_ the host, perhaps you've inadvertently omitted that?

**Comment by ThePieMonster** [comment]
Thanks for the response @davidnewhall. Currently these are the logs I have. Will try to figure out why it thinks its a directory. Maybe a issue with the mapping in the YAML file.

Error from Pod Events
`Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/var/snap/microk8s/common/var/lib/kubelet/pods/85149a67-b706-40c1-bba3-959e5129f091/volumes/kubernetes.io~configmap/default-token-unifi-poller" to rootfs at "/var/snap/microk8s/common/run/containerd/io.containerd.runtime.v2.task/k8s.io/unifi-poller/rootfs/etc/unifi-poller/up.conf" caused: not a directory: unknown`

Logs from Pod
![image](https://user-images.githubusercontent.com/11359134/106348033-a64bec80-6288-11eb-90f7-4ae25095f486.png)

**Comment by davidnewhall** [comment]
Yea, that's what I suspected. You're not mapping a config file to `/config/unifi-poller.conf`, you're just mapping an empty folder. Where's the source file? How do you put that in your yaml?

**Comment by ThePieMonster** [comment]
@davidnewhall Updated the config to the below and got things working.  👍

![image](https://user-images.githubusercontent.com/11359134/106348722-e82b6180-628d-11eb-9f8d-31a9f7f08e48.png)


```
kind: Pod
apiVersion: v1
metadata:
  name: unifi-poller
  namespace: default
spec:
  containers:
    - name: unifi-poller
      image: golift/unifi-poller
      volumeMounts:
      - name: default-volume-unifi-poller
        mountPath: /config/unifi-poller.conf
        subPath: unifi-poller.conf
  volumes:
    # `name` here must match the name specified in the volume mount
    - name: default-volume-unifi-poller
    # Populate the volume with config map data
      configMap:
        # `name` here must match the name specified in the ConfigMap's YAML
        name: unifi-poller
```
