### ISSUE TITLE
promunifi: (fix typo) Original title: Prometheus getting a Connection Refused when Scraping

### ISSUE THREAD

**Issue by michaelpietzsch** [unifi-poller/unifi-poller#303]
Hi guys,

heres my .conf segment

`      [prometheus]
        disable = false
        http_listen = "0.0.0.0:9130"
        report_errors = false `

I am using kubernetes to scrape the pod... autodiscovery works fine

`      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9130"
        prometheus.io/scrape: "true" `

But i am getting a connection refused from the pod any ideas?
![image](https://user-images.githubusercontent.com/11281151/106463586-e9c87580-6497-11eb-82a2-0451caf3205a.png)

**Comment by davidnewhall** [comment]
Need to pass through port 9130.

**Comment by michaelpietzsch** [comment]
@davidnewhall  what do you mean by that?

**Comment by davidnewhall** [comment]
I don't use Kubernetes, so I don't know. In Docker, you do it with `-p 9130:9130` when you run `docker run`.

**Comment by michaelpietzsch** [comment]
@davidnewhall  thanks for the input... but it works a bit different inside a k8s cluster...

**Comment by michaelpietzsch** [comment]
Ive found out that its using secure http now (https) can i disable that ?

**Comment by davidnewhall** [comment]
https is not the default. What makes you think it's using https? Have you gotten past `connection refused`?

**Comment by michaelpietzsch** [comment]
Ive looked in the logs.... `2021/02/02 08:27:24.981506 collector.go:134: [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller`  https....

**Comment by davidnewhall** [comment]
Can you show me your poller configuration?

**Comment by michaelpietzsch** [comment]
```       [poller]
          debug = true
          quiet = false
          plugins = []
      [influxdb]
          disable = false
          interval = "30s"
          url = "http://influx.monitoring.svc.cluster.local:8086"
          user = "SNHa8BctioiPK5adY9GX"
          pass = "PRIVATE"
          db = "maindb"
          verify_ssl = false
      [prometheus]
        disable = false
        http_listen = "0.0.0.0:9130"
        report_errors = false
      [unifi]
          dynamic = false
      [loki]
          url = "http://loki.monitoring.svc.cluster.local:3100"    
      [[unifi.controller]]
          url         = "https://10.30.0.1"
          user        = "unifipoller"
          pass        = "PRIVATE"
          sites       = ["all"]
          save_ids    = true
          save_dpi    = true
          save_sites  = true
          hash_pii    = false
          verify_ssl  = false
        [[unifi.controller]]
          url         = "https://10.1.0.1"
          user        = "unifipoller"
          pass        = "PRIVATE"
          sites       = ["all"]
          save_ids    = true
          save_dpi    = true
          save_sites  = true
          hash_pii    = false
          verify_ssl  = false
        [[unifi.controller]]
          url         = "https://10.10.0.12"
          user        = "unifipoller"
          pass        = "PRIVATE"
          sites       = ["all"]
          save_ids    = true
          save_dpi    = true
          save_sites  = true
          hash_pii    = false
          verify_ssl  = false  ```

**Comment by davidnewhall** [comment]
`https` appears to be a typo in the code, [here](https://github.com/unifi-poller/promunifi/blob/master/collector.go#L134). The application only listens on `http`. The listener is created a few lines later, [here](https://github.com/unifi-poller/promunifi/blob/master/collector.go#L141). The listener has no SSL cert or key, so it is http only. I will fix the typo in an update.

**Comment by davidnewhall** [comment]
Your config is comprehensive. A few questions:
1. You really have 3 different controllers? Curious: how many sites?
2. Are you using InfluxDB _and_ Prometheus?
3. Do you need to?

**Comment by michaelpietzsch** [comment]
@davidnewhall 
1. 3 Sites....
2. i am currently using InfluxDB aswell...
3. Well i wanted to eventually ditch the influx...
4. Influx works fine...

**Comment by davidnewhall** [comment]
What's the prometheus error? still connection refused?

**Comment by michaelpietzsch** [comment]
> What's the prometheus error? still connection refused?

yep..... maybe im overseeing something in the kubernetes config....

**Comment by davidnewhall** [comment]
What owns the IP `10.244.1.65` ? Are you familiar with passing ports through in k8s?

**Comment by michaelpietzsch** [comment]
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-poller
  namespace: monitoring
  labels:
    app: unifi-poller
    type: poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-poller
      type: poller
  template:
    metadata:
      labels:
        app: unifi-poller
        type: poller
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9130"
        prometheus.io/scrapesecure: "true"
    spec:
      containers:
      - name: unifi-poller
        image: golift/unifi-poller:latest
        ports:
        - containerPort: 9130
          name: tcp
          protocol: TCP
        - containerPort: 9130
          name: udp
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /config/unifi-poller.conf
          subPath: unifi-poller.conf

      volumes:
      - name: config-volume
        configMap:
          name: unifi-poller


```
